export const mockPosts = [
  {
    postId: 1,
    title: "럭키비키",
    nickname: "장원영",
    createdAt: "2025-03-31",
    viewCount: 165,
    likeCount: 12,
    commentCount: 3,
  },
  {
    postId: 2,
    title: "도와주세요",
    nickname: "카리나",
    createdAt: "2025-03-23",
    viewCount: 68,
    likeCount: 5,
    commentCount: 0,
  },
  {
    postId: 3,
    title: "잘 모르겠어요",
    nickname: "유나",
    createdAt: "2025-03-20",
    viewCount: 69,
    likeCount: 2,
    commentCount: 1,
  },
  {
    postId: 4,
    title: "프로젝트 뭐하지",
    nickname: "설윤",
    createdAt: "2025-03-16",
    viewCount: 40,
    likeCount: 1,
    commentCount: 0,
  },
  {
    postId: 5,
    title: "럭키비키",
    nickname: "장원영",
    createdAt: "2025-03-31",
    viewCount: 165,
    likeCount: 12,
    commentCount: 3,
  },
  {
    postId: 6,
    title: "도와주세요",
    nickname: "카리나",
    createdAt: "2025-03-23",
    viewCount: 68,
    likeCount: 5,
    commentCount: 0,
  },
  {
    postId: 7,
    title: "잘 모르겠어요",
    nickname: "유나",
    createdAt: "2025-03-20",
    viewCount: 69,
    likeCount: 2,
    commentCount: 1,
  },
  {
    postId: 8,
    title: "프로젝트 뭐하지",
    nickname: "설윤",
    createdAt: "2025-03-16",
    viewCount: 40,
    likeCount: 1,
    commentCount: 0,
  },
  {
    postId: 9,
    title: "럭키비키",
    nickname: "장원영",
    createdAt: "2025-03-31",
    viewCount: 165,
    likeCount: 12,
    commentCount: 3,
  },
  {
    postId: 10,
    title: "도와주세요",
    nickname: "카리나",
    createdAt: "2025-03-23",
    viewCount: 68,
    likeCount: 5,
    commentCount: 0,
  },
  {
    postId: 11,
    title: "잘 모르겠어요",
    nickname: "유나",
    createdAt: "2025-03-20",
    viewCount: 69,
    likeCount: 2,
    commentCount: 1,
  },
  {
    postId: 12,
    title: "프로젝트 뭐하지",
    nickname: "설윤",
    createdAt: "2025-03-16",
    viewCount: 40,
    likeCount: 1,
    commentCount: 0,
  },
  
 
];
